dev:
	pnpm --recursive --parallel run dev

build:
	cd vue-component && pnpm run build
	cd react-app && pnpm run build
	cd vue-app && pnpm run build
	cd layout-app && pnpm run build
	cd app && pnpm run build

preview:
	cd app && pnpm run preview
